version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: steam_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12344321m
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - steamnet

  backend:
    build:
      context: ../steam-clone-backend
      dockerfile: Dockerfile
    container_name: steam-clone-backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12344321m
      DB_NAME: steam_clone
    networks:
      - steamnet

volumes:
  postgres_data:

networks:
  steamnet:
    driver: bridge
